### ISSUE TITLE
Changes in font

### ISSUE THREAD

**Issue by boturnbow** [mhesac/www.masfaaonline.org#1]
@matthellwinkel in case you missed this - pretty obscure

I saw a mention of this https://github.com/JulietaUla/Montserrat/issues/60 and I knew that font name sounded familiar! Looks like there is documentation here: https://github.com/JulietaUla/Montserrat/releases/tag/v7.200

Enjoy!

**Comment by matthellwinkel** [comment]
Thanks for pointing this out. Pretty epic changes!

**Comment by boturnbow** [comment]
Pretty nuts when a font weight change makes the front page of hacker news! Lol
